### PR TITLE
COMPLETED PR for Epic-School-and-Term-validations-F5

### LINKED ISSUE #24: EPIC: School and Term validations (F5: Frontend Course Form uses school specific regex.)
- [x] After selecting a school on the course form, the regex for that school is loaded and applied to the value in the term field
- [x]  If the term field does not match the regex for that school, the school specific error message is displayed
- [x]  Any time the school is changed before the school is created or saved, the regex is reloaded and applied to the current value of term. If there is an error with the new regex, the new message is displayed.
- [x]  Any time the term field changes. the regex for the current school is applied to the new contents, and the error message updates if needed.
- [x]  When the school is entered, a term is entered, and the matching regex is satisfied, no error message displays and the user is permitted to save the new or updated school.

### PR DESCRIPTION
**Pull request by DemirInce**
When updating the term, the user must follow the regex format of the season followed by a 2 digit year. For ex. w24, s24, f24 or else it will display an error message. User also must update the term whenever editing the school as stated in #23 

Closes #24 
Deployed at: https://organic-thienanvuu-dev.dokku-10.cs.ucsb.edu
Screenshot 2024-03-12 at 5 37 32 PM

### CODE REVIEW

**Review by kjlee2504 — DISMISSED** [review]
LGTM

**Review by whuang602 — CHANGES_REQUESTED** [review]
Deployment does not seem to reflect the change, I can still submit term values that do not strictly follow the format of the regex. While it is true that it works for edit, there is currently no regex enforcement for create.

**Comment by thienanvuu** [comment]
I just implemented the term regex for create.

**Review by kjlee2504 — APPROVED** [review]
lgtm

**Pull request closed without merging**
