### PR TITLE
COMPLETED PR for Epic-School-and-Term-validations-F4

### LINKED ISSUE #23: EPIC: School and Term validations (F4: Frontend Course Form shows school specific term description)
- [x] After selecting a school on the course form, the text for the termDescription for that school will be displayed near the place where the user is supposed to enter the term
- [x]  Any time the school is changed before the school is created or saved, the termDescription text should change
- [x]  That's all for this issue. Get this working first before tackling the regex thing

### PR DESCRIPTION
**Pull request by DemirInce**
Will show an error message if user wants to edit the school without editing the term and user will be unable to change school unless they change the term as well
Screenshot 2024-03-12 at 5 38 27 PM

Closes #23 
Deployed at https://organic-thienanvuu-dev.dokku-10.cs.ucsb.edu

### CODE REVIEW

**Review by kjlee2504 — DISMISSED** [review]
LGTM

**Review by whuang602 — DISMISSED** [review]
LGTM, however I would appreciate it if you can make me an admin so I can test it. Currently I am approving this based on me having tried it on your localhost.

**Comment by thienanvuu** [comment]
I made you an admin

**Review by whuang602 — COMMENTED** [review]
I am going to be frank with you, I really doubt this is what the issue meant originally. 

Just this line alone "Any time the school is changed before the school is created or saved, the termDescription text should change" seems to suggest a different feature implementation.

No backend has been implemented, which in and of itself is a big _issue_, so valid schools cannot even be created or selected and their respective termDescription cannot be selected. However, I think it's unfair to punishing you for misunderstanding the issue description this late. I will double check with the other staff to see how to proceed with this PR.

**Pull request closed without merging**
