### PR TITLE
Vincent organic last online bug

### LINKED ISSUE #5: BUG: Last Online in User Profile Defaults to Wrong Date
### Have you updated the title?

- [X] I have updated the issue's title.

### Summary

Under the user profile page in the Organic web app, the Last Online value is always set to be 1/20/1970. (5)

(Note: 1/1/1970 is the unix epoch)

### Expected Behavior

The value should be updated to "Online now" or something more appropriate. 

### Current / Observed Behavior

Currently, the Last Online value does not accurately reflect what the user's activity status is.

### Steps to Reproduce

1. Login with GitHub OAuth
2. Click the top right "Welcome, user" text
3. The topmost table indicates the wrong date for "Last Online"
4.

### Browser / Platform Info

_No response_

### PR DESCRIPTION
**Pull request by vincentlinzhu**
Fixed the lastOnline display bug in the user profile table. Additionally, changed interceptor casing for import.

Screenshot:
Screenshot 2024-03-05 at 6 33 39 PM

Screenshot 2024-03-05 at 7 10 24 PM

Deployment Link: https://organic-vincentlinzhu-dev.dokku-10.cs.ucsb.edu

Closes #5

### CODE REVIEW

**Review by DemirInce — DISMISSED** [review]
LGTM!

**Review by DemirInce — DISMISSED** [review]
LGTM!

**Review by whuang602 — CHANGES_REQUESTED** [review]
Actually, it would be great if you can modify the folder to be lowercase i and revert the package name change.

**Review by kjlee2504 — APPROVED** [review]
LGTM

**Review by whuang602 — APPROVED** [review]
LGTM

**Pull request merged**
