### PR TITLE
KL - FEATURE: [Frontend] Normal User Join Action

### LINKED ISSUE #7: FEATURE: [Frontend] Normal User Join Action
### Have you updated the title?

- [X] I have updated the issue's title.

### As a...

normal user (student)

### I can...

click on a join button

### So that...

I can join the course's Github Organization

### Discussion

This issue assumes that the student user can now access the courses page. Create a frontend button that the normal user can click. (5)

### Acceptance Criteria

- [x] Normal user can see a "Join" (or similarly named) button in the courses table
- [x] Normal user can actually click on the button (no backend for now)

### Implementation Todos

Frontend:
- [x] Normal user instead of seeing edit or delete, can see a join button
- [x] Join button can be clicked but does not do anything (for now)

Testing:
- [x] Front end tests pass and there is adequate coverage
- [x] Back end tests pass and there is adequate coverage

### PR DESCRIPTION
**Pull request by kjlee2504**
Normal users can now see the "Join" button to join a course. Currently it is only frontend and clicking the button does nothing.
Deployed at: https://organic-kjlee2504-dev.dokku-10.cs.ucsb.edu/
Screenshot 2024-03-02 at 5 25 23 PM
Closes #7

### CODE REVIEW

**Review by thienanvuu — APPROVED** [review]
looks great

**Review by whuang602 — CHANGES_REQUESTED** [review]
As a non admin, I cannot see anything in the course table. Therefore I cannot even create a new entry to test whether the join button works.

**Review by thienanvuu — APPROVED** [review]
looks good to me

**Comment by kjlee2504** [comment]
fixed

**Review by whuang602 — APPROVED** [review]
LGTM

**Pull request merged**
