### PR TITLE
Demir pop up when toggle

### LINKED ISSUE #4: FEATURE: Pop-ups for Admin Toggles
### Have you updated the title?

- [X] I have updated the issue's title.

### As a...

admin

### I can...

receive a pop-up when I try to toggle roles

### So that...

I can accurately decide whether I want to alter roles

### Discussion

Currently, admins can modify other users' roles with one click. This can be detrimental if it wasn't done intentionally, this can also potentially result in problems for other admins. A pop-up or confirmation request would be a great change that ensures security and user safety. (10)

### Acceptance Criteria

- [ ] When an admin clicks on "toggle-admin" they get a pop up that asks them if they are sure they want to toggle admin role
- [ ] When an admin clicks on "toggle-instructor" they get a pop up that asks them if they are sure they want to toggle instructor role

### Implementation Todos

Frontend:
- [ ] Add a confirmation popup before the toggle backend is triggered (feel free to look up how to do this)

Testing:
- [ ] Front end tests pass and there is adequate coverage
- [ ] Back end tests pass and there is adequate coverage

### PR DESCRIPTION
**Pull request by DemirInce**
After pressing the admin or instructor toggle buttons, a popup window for confirmation appears.

Installed React Model to handle popup windows.

Screenshot 2024-03-05 at 17 49 14

Closes #4 

Deployed at: https://organic-demirince-dev.dokku-10.cs.ucsb.edu

### CODE REVIEW

**Review by kjlee2504 — CHANGES_REQUESTED** [review]
a deployment link would be nice

**Comment by DemirInce** [comment]
> a deployment link would be nice

ITS ALREADY THERE

**Review by kjlee2504 — DISMISSED** [review]
LGTM

**Comment by DemirInce** [comment]
pls merge

**Review by vincentlinzhu — APPROVED** [review]
Awesome job: Passes all the tests (including the added tests by Demir). This is not the most important thing but it would be nice to add an explanation for the use of the "Stryker disable all" comment. This would help put future iterations of the class with understanding all the new stuff you added.

**Review by whuang602 — APPROVED** [review]
LGTM

**Pull request merged**
