### PR TITLE
COMPLETED Fixed Course Dates Bug 

### LINKED ISSUE #8: BUG: Course Can End Before It Starts
### Have you updated the title?

- [X] I have updated the issue's title.

### Summary

Currently, if you create a course (as an admin) under the Courses tab (top left) you can set the end date of the course to be before it even starts.  This shouldn't be possible. (5)

### Expected Behavior

Presumably, the course should end sometime _after_ the course starts.

### Current / Observed Behavior

Currently, there's no logic being enforced on the start and end date. So they can quite literally be whatever value, which doesn't make as much sense as we would like.

### Steps to Reproduce

1. Click on Courses in the top left
2. Create a course
3. Input an end date that is sometime BEFORE the start date
4.

### Browser / Platform Info

_No response_

### PR DESCRIPTION
**Pull request by mbharti12**
Added checks to make sure that start date comes before end date (added checks to the backend and frontend). Can test this on dokku by trying out different values for the start and end date fields on the update/create pages: https://organic-mbharti12-dev.dokku-10.cs.ucsb.edu.

#### _Backend:_

Screenshot 2024-03-12 at 12 31 48 AM

In CoursesController.java, I added a check to the postCourse api call that ensures that startDate is strictly less than endDate in a post request. If not, a Bad Request is returned.

Screenshot 2024-03-12 at 12 33 47 AM

I made the same change in the update request.

Screenshot 2024-03-12 at 12 35 53 AM

In CoursesControllerTests.java, I added two tests that check if the postCourse request returns a Bad Request if startDate is greater than or equal to endDate.

Screenshot 2024-03-12 at 12 37 17 AM

In CoursesControllerTests.java, I added two tests that check if the updateCourse request returns a Bad Request if startDate is greater than or equal to endDate.

#### _Frontend:_

Screenshot 2024-03-12 at 12 28 56 AM

In CoursesForm.js, I added a check that ensures that startDate is strictly less than endDate when the user enters them in the form.

Screenshot 2024-03-12 at 12 42 16 AM
Screenshot 2024-03-12 at 12 42 59 AM

In CoursesForm.test.js, I added two tests that check if the correct message is outputted when startDate is greater than or equal to endDate.

Screenshot 2024-03-12 at 12 48 38 AM
Screenshot 2024-03-12 at 12 49 15 AM
Screenshot 2024-03-12 at 12 49 33 AM

I edited some existing tests in CoursesEditPage.test.js so that the start dates initialized in these tests come before the end dates that are initialized in these tests (since the tests are supposed to be testing on good inputs).

Closes #8

### CODE REVIEW

**Review by thienanvuu — DISMISSED** [review]
lgtm

**Review by whuang602 — CHANGES_REQUESTED** [review]
Please dont just say that it's easy to test on localhost or on deployment without actually providing a deployment link. This makes life harder for people reviewing your PR, i.e. your teammates and potential manager/leads.

**Review by kjlee2504 — APPROVED** [review]
lgtm

**Review by whuang602 — APPROVED** [review]
LGTM, but one key note:
when I said add images to your PR, I don't mean adding screenshots of code. I meant adding images of what changes reviewers may see in the front end. This allows them to see the intended effects (in case there's difference between your local machine and the deployed version for reviewers)

**Pull request merged**
