### PR TITLE
COMPLETED PR for Epic-School-and-Term-validations-F2

### LINKED ISSUE #21: EPIC: School and Term validation (F2: Frontend Create and Index Pages)
**ALREADY COMPLETED by staff (F1: Frontend: Form)**
- [x]  Add "School" to the navbar
- [x]  Implement the Table for School (actual table, tests, storybooks)
- [x]  Index Page that uses table with link to delete and edit pages
- [x]  Create Page that uses form
- [x]  Edit page frontend.

### PR DESCRIPTION
**Pull request by vincentlinzhu**
Added School Table, Index, Create, Edit Pages (w/ stories, w/ tests); 

Storybook Links: 
- https://ucsb-cs156-w24.github.io/proj-organic-w24-6pm-2/prs/44/storybook/?path=/story/components-school-schooltable--three-items-admin-user
- https://ucsb-cs156-w24.github.io/proj-organic-w24-6pm-2/prs/44/storybook/?path=/story/pages-school-schoolcreatepage--default

Deployment Link: https://organic-vincentlinzhu-dev.dokku-10.cs.ucsb.edu/

Since the backend is not implemented, there is no way to navigate to the edit page. Here is a link to a blank edit page. The fields would populate if the get call hadn't failed. There are tests to verify this.
Edit Page: https://organic-vincentlinzhu-dev.dokku-10.cs.ucsb.edu/school/edit/1

Screenshots: 
Screenshot 2024-03-11 at 4 47 08 PM

Screenshot 2024-03-11 at 4 47 33 PM

Screenshot 2024-03-11 at 4 47 51 PM

Screenshot 2024-03-11 at 4 48 17 PM

Closes #21

### CODE REVIEW

**Review by kjlee2504 — DISMISSED** [review]
lgtm

**Comment by DemirInce** [comment]
> lgtm

that's not a review

**Review by DemirInce — APPROVED** [review]
LGTM!

**Review by DemirInce — CHANGES_REQUESTED** [review]
Works fine on local, on dokku school page is blank.

**Review by DemirInce — DISMISSED** [review]
LGTM!!!!!

**Review by DemirInce — APPROVED** [review]
LGTM!!! for the final time please

**Review by whuang602 — APPROVED** [review]
LGTM, Vincent explained in OH that there isn't a backend. This PR is still mergeable.

**Pull request merged**
