### PR TITLE
Instructor can create, edit, delete a course

### LINKED ISSUE #2: FEATURE: Instructors can create courses
# Dependencies

This issue cannot be started until after there has been enough progress on the Epic for creating the Instructor role so that ROLE_INSTRUCTOR exists in the database.

# User Story

* As an instructor
* I can create a new course
* So that I don't have to rely on admins to create courses

### Discussion

This issue cannot be started until after there has been enough progress on the Epic for creating the Instructor role so that ROLE_INSTRUCTOR exists in the database.

Currently, only Admins can create courses.

In this issue, we'll modify that so that Instructors can also create courses.

Once an instructor creates a course, they will be automatically a staff member for that course so that will be the way in which we determine whether or not they have permissions to do course management features.  So only the creation of the course is affected.

For now, we'll assume that only admins can delete a course.

### Acceptance Criteria

- [ ] Anyone with ROLE_ADMIN or ROLE_INSTRUCTOR can create a course.
- [ ] The frontend access to creating a course only shows up for users with  ROLE_ADMIN or ROLE_INSTRUCTOR

### PR DESCRIPTION
**Pull request by DemirInce**
Admin & not instructor, not admin & instructor and not admin & not instructor users can all create, edit, delete a course.

Deployed: https://organic-demirince-dev.dokku-10.cs.ucsb.edu

Closes #2

### CODE REVIEW

**Review by whuang602 — CHANGES_REQUESTED** [review]
would love to see a deployment link and approval from fellow teammates

**Comment by DemirInce** [comment]
> would love to see a deployment link and approval from fellow teammates

deployed at: https://organic-demirince-dev.dokku-10.cs.ucsb.edu

**Review by kjlee2504 — DISMISSED** [review]
LGTM!

**Review by kjlee2504 — DISMISSED** [review]
LGTM

**Review by kjlee2504 — CHANGES_REQUESTED** [review]
Fix your mutations

**Review by whuang602 — CHANGES_REQUESTED** [review]
if you have commented out code, just remove it. - Prof Conrad (he would definitely say this)

**Review by kjlee2504 — APPROVED** [review]
LGTM

**Review by whuang602 — APPROVED** [review]
LGTM

**Pull request merged**
